vim.keymap.set('n', '<leader>1', ':lua require("harpoon.ui").nav_file(1)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>2', ':lua require("harpoon.ui").nav_file(2)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>3', ':lua require("harpoon.ui").nav_file(3)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>4', ':lua require("harpoon.ui").nav_file(4)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>5', ':lua require("harpoon.ui").nav_file(5)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>6', ':lua require("harpoon.ui").nav_file(6)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>7', ':lua require("harpoon.ui").nav_file(7)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>8', ':lua require("harpoon.ui").nav_file(8)<CR>', {noremap = true})
vim.keymap.set('n', '<leader>9', ':lua require("harpoon.ui").nav_file(9)<CR>', {noremap = true})

vim.keymap.set('n', 'mm', ':lua require("harpoon.mark").add_file()<CR>', {noremap = true})

-- require("telescope").load_extension('harpoon')
-- vim.keymap.set('n', '<leader>m', ':Telescope harpoon marks<CR>', {noremap = true})
vim.keymap.set('n', '<leader>n', ':lua require("harpoon.ui").toggle_quick_menu()<CR>', {noremap = true})
vim.keymap.set('n', '<leader>m', ':Telescope harpoon marks<CR>', {noremap = true})
