require("mine/plug")
require("mine/keymap")
require("mine/opt")
require("mine/lsp")
require("mine/gx")
require("mine/minimap")
require("mine/prettier")
require("mine/harpoon")
-- require("mine/noiceconfig")
